import type { Metadata } from "next";
import { SiteFooter } from "../../components/site-footer";
import { SiteHeader } from "../../components/site-header";

export const metadata: Metadata = { title: "About", description: "About Zavier Rodrigues—software engineer, Berkeley student, tutor, and writer.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <div className="site-shell"><SiteHeader /><main className="about-page section-pad"><section className="about-hero"><div><p className="eyebrow">About me</p><h1>I like the moment when a difficult idea becomes clear.</h1></div><div className="about-shape"><span>curious<br />by default</span></div></section><section className="about-story"><aside><div className="portrait-placeholder large"><span>ZR</span></div><p>Portrait placeholder</p></aside><article><p className="about-lede">I’m Zavier Sean Rodrigues, a software engineer and student at UC Berkeley studying Computer Science and Economics.</p><p>I’m drawn to work that sits between disciplines: software and behavior, systems and stories, technical ambition and everyday usefulness. I enjoy taking an idea from its first uncertain sketch to a product people can actually understand and trust.</p><p>Teaching matters to me for the same reason. Good tutoring isn’t about making something seem easy—it’s about helping someone build the map that lets them move through difficulty on their own.</p><p>And then there’s poetry: a different way of paying attention, but part of the same practice of noticing structure, meaning, and what people carry with them.</p><div className="button-row"><span className="primary-button disabled-link" aria-disabled="true" title="Add a verified resume before launch">Resume coming soon</span><a className="secondary-button" href="https://github.com/ZavierRod">GitHub <span>↗</span></a></div></article></section><section className="currently"><p className="eyebrow">Currently</p><div><article><span>Learning</span><h2>Computer Science + Economics</h2><p>UC Berkeley</p></article><article><span>Building</span><h2>Products with a point of view</h2><p>Across iOS, web, and mobile</p></article><article><span>Writing</span><h2>Poetry that pays attention</h2><p>Shared here when it’s ready</p></article></div></section><section className="about-cta"><h2>Want to build or learn together?</h2><p>I’m open to thoughtful software opportunities, collaboration, and tutoring conversations.</p><span className="primary-button disabled-link" aria-disabled="true">Contact details coming soon</span><small>A verified public email will replace this before launch.</small></section></main><SiteFooter /></div>;
}
